name: CI

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: thedeveloperden/haste-server
          tags: ${{ steps.package-version.outputs.current-version }}
          tag_with_ref: true
